-- USER_ID 기준으로 USER_INFO ONLINE_SALE 두 테이블 JOIN
-- YEAR / MONTH / GENDER 는 ONLINE_SALE 테이블 SALES_DATE 에서 추출 
-- DISTINCT 로 중복제거 필요 (동일한 날짜, 회원 ID, 상품 ID 조합)
-- GENDER 가 NULL 이면 결과에서 제외 
-- YEAR / MONTH / GENDER 기준 오름차순 

SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O
JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER ASC