-- 식당 데이터 JOIN 연산 
-- 식당 번호 기준으로 GROUP BY 연산 / ROUND, AVG로 결과값 출력 
-- 서울 식당 필터링 : HAVING, LIKE
-- 평균점수로 내림차순, 평균점수 같다면 즐겨찾기수로 내림차순 : ORDER BY 

SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A
JOIN REST_INFO B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID HAVING B.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, B.FAVORITES DESC