-- JOIN 으로 테이블 3개 합치기
-- WHERE : 취소 안 된 값, CS값, 날짜 '2022-04-13' 으로 필터링 
-- ORDER BY : 진료예약일시로 오름차순 

SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
JOIN PATIENT P ON P.PT_NO = A.PT_NO
WHERE A.APNT_CNCL_YMD IS NULL AND A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE '2022-04-13%'
ORDER BY A.APNT_YMD ASC