-- ANIMAL_ID 기준으로 ANIMAL_OUTS 테이블을 LEFT JOIN
-- DATETIME 비교해서 ANIMAL_OUTS 테이블의 DATETIME 이 더 앞이면 출력 
-- I.DATETIME 빠른 순으로 정렬 (오름차순)

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC